### ISSUE TITLE
conf

### ISSUE THREAD

**Issue by ghost** [sbalian/quantum-random#11]
ANU requires you to use an API key. You can get a free trial or pay for a key [here](https://quantumnumbers.anu.edu.au/pricing).

You can pass your key to qrandom in three ways:

By setting the environment variable QRANDOM_API_KEY.
By running the included command line utility qrandom-init to save your key in qrandom.ini in a subdirectory of your home config directory as specified by XDG, e.g., /home/<your-username>/.config/qrandom/.
By running qrandom-init to save your key in qrandom.ini in a directory of your choice, and then specifying this directory by setting QRANDOM_CONFIG_DIR.
If QRANDOM_API_KEY is set, its value is used as the API key and the config file is not read. Otherwise, qrandom will look for the key in the config directory. The config directory defaults to the XDG home config and can be changed by setting QRANDOM_CONFIG_DIR.

--------------
Hello,
the only thing that works here is  qrandom-init and saving the key in ~home/.config/qrandom directory.
Everything else via py3.12.1 will not work!
Why recommend three ways when two are plainly not working!

I run MX-linux and winpro10

**Comment by sbalian** [comment]
I have not actually tested for Python 3.12. I can do that. In the meantime, can you please try and see if things work for you on Python 3.11 or less?

Also, what do you mean "everything else will not work"? What did you try exactly and what kind of errors did you get if any?

**Comment by ghost** [comment]
~user/.config/qrandom/key works with API
if in winpro10 I add QRANDOM_API_KEY=12345hlsjdlsj....
it does not
if I add key in random directory in my project and use other alternative method also does not work.

So of three ways to include a key only thing that works is ~user/.config/qrandom/

btw stuff works in 3.12.1 

I just do not want key to be in unix user home directory but ratter to coexist with other stuff in project...

Regards,

**Comment by sbalian** [comment]
Thanks. The two methods that are not working for you involve setting environment variables. Can you tell me how you're doing this on Windows? Have you managed to use environment variables for other projects successfully? Perhaps write a simple python script that just tries to print os.environ["MY_VAR"].

**Comment by ghost** [comment]
Windows, who in the right mind uses mini os. I do not use windows at all. I use Unix, in this case mx linux.
when you say env... you can stash variable in .bashrc as key=value pair
then i used in winpro10 (IDE) as project property python env key=value pair

both ways code base would not pick it up ...
like I said only way is to stash into ~user/.config/qrandom/key

sourcing .bashrc works and I do see key:value pair
I know that project properties in wingpro10 do load env variables as I have couple of variables there that are used with templating python headers with right values ...
Try it is unix and let me know if it works for you...
Maybe I am doing something really stupid ...

hope this helps...

**Comment by sbalian** [comment]
wingpro10 or winpro10? Above you kept writing "winpro10" which made me think you are using Windows. I understand now that you are referring to a Python IDE. Anyway, if you are on Unix, can you please run the following and paste what it says here:

1. Copy your API key to somewhere safe if you have not done so, then delete the file `~/.config/qrandom/qrandom.ini`.
2. Run the following commands:

```bash
export QRANDOM_API_KEY=your-key
python -c "import qrandom; print(qrandom.random())"
```

3. Paste what you get here. For me on 3.12.1, I get a random number printed as expected. When I set the environment variable to an incorrect key, I get an error. So everything is working fine on 3.12.1 for me.

**Comment by ghost** [comment]
> wingpro10 or winpro10? Above you kept writing "winpro10" which made me think you are using Windows. I understand now that you are referring to a Python IDE. Anyway, if you are on Unix, can you please run the following and paste what it says here:
> 
> 1. Copy your API key to somewhere safe if you have not done so, then delete the file `~/.config/qrandom/qrandom.ini`.
> 2. Run the following commands:
> 
> ```shell
> export QRANDOM_API_KEY=your-key
> python -c "import qrandom; print(qrandom.random())"
> ```
> 
> 3. Paste what you get here. For me on 3.12.1, I get a random number printed as expected. When I set the environment variable to an incorrect key, I get an error. So everything is working fine on 3.12.1 for me.

Hi, yes it is wingpro10 ide, sorry about misspell. It works on terminal, I need to figure out why is not working  when debugging in IDE...
Also, quantum RN generation seems to me expensive contract if I need a millions ints for my sample.
I will need to figure out some other services that are free or cheaper than anu...

**Comment by sbalian** [comment]
Added 3.12 tests. To be merged soon, closing this.
